### ISSUE TITLE
Please update Documentation

### ISSUE THREAD

**Issue by thesequelgroup** [fulcrumapp/fulcrum-desktop#12]
This is not a bug but rather an enhancement suggestion.

It should say somewhere in the documentation that you can pass --pg-user, --pg-password and --pg-database to the sync command. I get a connection error unless I explicitly pass these:

**./fulcrum sync --org 'MyOrgName' --pg-user johndoe --pg-password johndoe password --pg-database foo_database --forever**

It's shown that you can do it in a Gist:
https://gist.github.com/oeon/6547c13c9c22c8b6f013fe737fe154b0

This should be documented as well as any other methods that allow the user of username / password.
Thanks!

**Comment by oeon** [comment]
Thanks for the feedback. I've made an addition to the developer docs to reflect this https://github.com/fulcrumapp/developer.fulcrumapp.com/commit/41fce09b3f3e836b945bfb0b84d418005dc24271.

If you spot anything else please let us know, or our [dev docs](https://github.com/fulcrumapp/developer.fulcrumapp.com) are open and PR's are welcome!
