### ISSUE TITLE
Postgres setup error - window related

### ISSUE THREAD

**Issue by Whatsupcory** [fulcrumapp/fulcrum-desktop#16]
[reported from customer messaging platform]

![postgres](https://user-images.githubusercontent.com/169266/38200717-6848dd34-3663-11e8-84f0-476f30aa603a.JPG)
I ran the command line commnd to create postgres extension, but got the error message. It is the most recent Fulcrum Desktop

I have since tried windwos 7, windows 2012 server, windows 2008 server and windows 10.

My understanding is that the GitHub made changes Feb and TLS 1.0 and 1.1 are no longer supported. Please let your developer know that might be the cause.

For windows 10 michine, I can setup, sgnc with no problem, But as soon as I install the postgres plugin, we will no longer able to sync anymore. I have duplicated the problem using different machine and networks. I am attaching a screenshot

![fulcrumerror](https://user-images.githubusercontent.com/169266/38200667-3cee243c-3663-11e8-9fec-7b9bc42a6e9c.jpg)

It is definitely a plugin problem. If you delete the plug in folder then the error goes away, if you put it back then errors out again. please have your developer check the code that sepeficed in the error message. thanks

**Comment by encleadus** [comment]
We could manage to install the plugin using this: https://support.microsoft.com/en-us/help/3140245/update-to-enable-tls-1-1-and-tls-1-2-as-a-default-secure-protocols-in

**Comment by oeon** [comment]
Closing this as per @encleadus's feedback (thank you!).
