### ISSUE TITLE
When setting up PostgreSQL database Error Role does not exist

### ISSUE THREAD

**Issue by geofbaum** [fulcrumapp/fulcrum-desktop#7]
While going through the setup and after installing the PostgreSQL plugin I went to the next step of setting up the database however, when I run the command I'm getting an error that role "my user name on the computer" does not exist. I have gone into my Fulcrum account and added a role with my exact username  but it still is giving me that error.

**Comment by zhm** [comment]
This is an issue with the `psql` command it sounds like. You might have to pass an explicit username to psql depending on your postgres installation and configuration.
